"""Offline unit tests only; no live Shopping or model performance claims."""

import importlib
import json
import hashlib
from concurrent.futures import ThreadPoolExecutor
from contextlib import contextmanager, nullcontext
from pathlib import Path
from threading import Barrier, Lock
from types import SimpleNamespace

import pytest
from mas_faults.shopping_action_protocol import MultiStateShoppingExecutor


@pytest.fixture
def probe():
    name = "scripts.probe_multimechanism_parallel"
    assert importlib.util.find_spec(name) is not None, "parallel probe is not implemented"
    return importlib.import_module(name)


TASKS = [
    {"task_id": "tea-up", "product_title": "Tea", "product_url": "http://127.0.0.1:17770/tea",
     "initial_quantity": 1, "quantity": 2},
    {"task_id": "tea-down", "product_title": "Tea", "product_url": "http://127.0.0.1:17770/tea",
     "initial_quantity": 3, "quantity": 1},
]


def observation(task, quantity):
    p = {"task_id": task["task_id"], "product_title": "Tea", "product_id": "12", "sku": "TEA",
         "requested_quantity": task["quantity"], "observed_quantity": quantity,
         "cart_verified": quantity == task["quantity"]}
    return {**p, "evidence": json.dumps(p)}


class UnitSession:
    """Fake responses only: receipts are generated by the actual executor."""
    def __init__(self, identity, shared):
        self.identity, self.shared, self.quantity = identity, shared, 0
        self.updated = False

    def response(self, url, data=None, text=None):
        body = text if text is not None else json.dumps(data)
        return SimpleNamespace(status_code=200, url=url, text=body, content=body.encode(),
                               json=lambda: data, raise_for_status=lambda: None)

    def item(self):
        quantity = self.shared.get("quantity", self.quantity) if self.shared is not None else self.quantity
        return {"item_id": 17, "sku": "TEA", "name": "Tea", "qty": quantity}

    def get(self, url, **kwargs):
        if "/guest-carts/" in url:
            return self.response(url, [self.item()])
        return self.response(url, text='<input name="product" value="12"><div data-product-sku="TEA">')

    def post(self, url, **kwargs):
        if url.endswith("/guest-carts"):
            return self.response(url, str(self.identity))
        self.quantity += kwargs["json"]["cartItem"]["qty"]
        if self.updated and self.shared is not None:
            self.shared["quantity"] = self.quantity
        return self.response(url, self.item())

    def put(self, url, **kwargs):
        self.quantity = kwargs["json"]["cartItem"]["qty"]
        if self.shared is not None:
            self.shared["quantity"] = self.quantity
        return self.response(url, self.item())

    def close(self):
        pass


class UnitExecutor(MultiStateShoppingExecutor):
    """Real adapter with injected HTTP; not proof of Magento semantics."""
    def __init__(self, identity, trace, *, shared=None):
        super().__init__("http://127.0.0.1:17770")
        self.session.close()
        self.session = UnitSession(identity, shared)
        self.identity, self.trace = identity, trace

    def add_to_cart(self, task):
        self.trace.append((self.identity, "INIT"))
        return super().add_to_cart(task)

    def add_quantity(self, task, quantity):
        self.trace.append((self.identity, "POST"))
        self.session.updated = True
        return super().add_quantity(task, quantity)

    def set_quantity(self, task, quantity):
        self.trace.append((self.identity, "PUT"))
        self.session.updated = True
        return super().set_quantity(task, quantity)

    def reobserve_cart(self, task):
        self.trace.append((self.identity, "GET"))
        return super().reobserve_cart(task)


def executor_factory(*, same_cart=False, cross_talk=False):
    instances, trace, shared = [], [], {} if cross_talk else None
    lock = Lock()

    def create(base):
        with lock:
            executor = UnitExecutor(0 if same_cart else len(instances), trace, shared=shared)
            instances.append(executor)
            return executor
    return create, instances, trace


@pytest.fixture
def args(tmp_path, monkeypatch):
    manifest = tmp_path / "tasks.json"
    manifest.write_text(json.dumps({"tasks": TASKS}))
    for key, value in {"LLM_PROVIDER": "modelscope_local", "LLM_MODEL": "Qwen/Qwen3.8-27B",
                       "LLM_BASE_URL": "http://127.0.0.1:18001/v1", "LLM_API_KEY": "unit-only"}.items():
        monkeypatch.setenv(key, value)
    return SimpleNamespace(task_manifest=manifest, task_ids=[t["task_id"] for t in TASKS],
                           output_dir=tmp_path / "probe", base_url="http://127.0.0.1:17770", topology="sequential")


def test_busy_lock_precedes_output_factories_and_network(probe, args):
    @contextmanager
    def busy():
        raise RuntimeError("busy")
        yield

    def forbidden(*a, **kw):
        pytest.fail("busy probe must perform no external work")

    with pytest.raises(RuntimeError, match="busy"):
        probe.run_probe(args, workflow_lock=busy, platform_name="linux", preflight=forbidden,
                        executor_factory=forbidden, batch_runner=forbidden, transport=forbidden)
    assert not args.output_dir.exists()


def test_actual_shared_lock_refuses_a_second_probe(probe, args, tmp_path):
    lock = lambda: probe.runner.locked_workflow(tmp_path / "workflow.lock")
    with lock(), pytest.raises(RuntimeError):
        probe.run_probe(args, workflow_lock=lock, platform_name="linux")
    assert not args.output_dir.exists()


@pytest.mark.parametrize("platform", ["darwin", "win32"])
def test_nonlinux_refuses_before_output_or_network(probe, args, platform):
    with pytest.raises(ValueError, match="Linux"):
        probe.run_probe(args, platform_name=platform)
    assert not args.output_dir.exists()


@pytest.mark.parametrize("field,value", [("LLM_PROVIDER", "deepseek"), ("LLM_MODEL", "other"),
                                          ("LLM_BASE_URL", "https://other.invalid/v1")])
def test_nonlocal_model_settings_rejected_offline(probe, args, monkeypatch, field, value):
    monkeypatch.setenv(field, value)
    with pytest.raises(ValueError):
        probe.run_probe(args, workflow_lock=nullcontext, platform_name="linux")
    assert not args.output_dir.exists()


def test_exact_manifest_pair_is_preserved_not_synthesized(probe, args):
    assert probe.select_tasks(args.task_manifest, args.task_ids, args.base_url) == TASKS
    with pytest.raises(ValueError):
        probe.select_tasks(args.task_manifest, ["missing", "tea-down"], args.base_url)


@pytest.mark.parametrize("change", [{"product_url": "http://127.0.0.1:17770/other"},
                                    {"quantity": 2}, {"product_url": "http://other.invalid/tea"}])
def test_manifest_pair_requires_same_product_distinct_targets_and_origin(probe, args, change):
    args.task_manifest.write_text(json.dumps([TASKS[0], {**TASKS[1], **change}]))
    with pytest.raises(ValueError):
        probe.select_tasks(args.task_manifest, args.task_ids, args.base_url)


def test_http_gate_rechecks_both_only_after_both_updates(probe):
    factory, instances, trace = executor_factory()
    result = probe.http_isolation_gate(TASKS, "http://127.0.0.1:17770", executor_factory=factory)
    assert result["passed"] is True
    assert len(instances) == 2
    last_write = max(i for i, (_, method) in enumerate(trace) if method in {"POST", "PUT"})
    assert [method for _, method in trace[last_write + 1:]] == ["GET", "GET"]
    assert len({f["cart_id_sha256"] for f in result["flows"]}) == 2
    assert [f["recheck"]["observed_quantity"] for f in result["flows"]] == [2, 1]


@pytest.mark.parametrize("option", ["same_cart", "cross_talk"])
def test_http_isolation_failure_stops_before_model_preflight(probe, args, option):
    factory, _, _ = executor_factory(**{option: True})
    def forbidden(*a, **kw):
        pytest.fail("failed HTTP gate must not reach a model")
    result = probe.run_probe(args, workflow_lock=nullcontext, platform_name="linux", transport=nullcontext,
                            executor_factory=factory, preflight=forbidden, batch_runner=forbidden)
    assert result["passed"] is False
    assert result["status"] == "http_gate_failed"
    assert json.loads((args.output_dir / "http_gate.json").read_text())["passed"] is False
    assert not (args.output_dir / "trials.jsonl").exists()
    assert (args.output_dir / "summary_zh.md").is_file()


def test_existing_output_is_never_reused(probe, args):
    args.output_dir.mkdir()
    marker = args.output_dir / "keep"
    marker.write_text("unchanged")
    with pytest.raises(FileExistsError):
        probe.run_probe(args, workflow_lock=nullcontext, platform_name="linux")
    assert marker.read_text() == "unchanged"
    assert list(args.output_dir.iterdir()) == [marker]


def unit_result(spec):
    executor = UnitExecutor(spec["trial_id"], [])
    executor.add_to_cart(spec["task"])
    executor.reobserve_cart(spec["task"])
    return {"trial_id": spec["trial_id"], "task_id": spec["task"]["task_id"],
            "cart_id_sha256": executor._cart_hash(), "http_receipts": executor.http_receipts,
            "result": {"session_id": spec["trial_id"]},
            "round": spec["round"], "mode": spec["mode"], "passed": True, "status": "completed",
            "usage_complete": True, "total_tokens": 12, "prompt_tokens": 10, "completion_tokens": 2,
            "model_calls": 1, "latency_seconds": 100, "model": "Qwen/Qwen3.8-27B", "provider": "modelscope_local"}


def test_crossover_eight_unique_trials_max_two_and_batch_wall_not_latency_sum(probe, tmp_path):
    clock = iter([0, 10, 20, 25, 30, 34, 40, 48])
    seen, widths = [], []
    barrier = Barrier(2)
    def run(spec):
        seen.append(spec)
        if spec["mode"] == "parallel":
            barrier.wait(timeout=3)
        return unit_result(spec)
    def pool(max_workers):
        widths.append(max_workers)
        return ThreadPoolExecutor(max_workers=max_workers)
    result = probe.run_batches(TASKS, tmp_path, {}, "http://127.0.0.1:17770", "sequential",
                               trial_runner=run, pool_factory=pool, clock=lambda: next(clock))
    assert widths == [1, 2, 2, 1]
    assert [(b["round"], b["mode"]) for b in result["batches"]] == [(1, "sequential"), (1, "parallel"), (2, "parallel"), (2, "sequential")]
    assert [b["wall_seconds"] for b in result["batches"]] == [10, 5, 4, 8]
    assert len(seen) == len({s["trial_id"] for s in seen}) == 8
    assert len({s["ledger_path"] for s in seen}) == 8
    assert all(s["job"]["arm"] == "baseline" and s["job"]["condition"] == "clean" for s in seen)
    assert [r["speedup"] for r in result["rounds"]] == [2, 2]
    assert result["passed"] is True


def test_error_is_retained_without_retry_and_unknown_usage_is_not_zero(probe, tmp_path):
    calls = []
    def run(spec):
        calls.append(spec["trial_id"])
        if len(calls) == 1:
            raise RuntimeError("unit failure")
        return unit_result(spec)
    result = probe.run_batches(TASKS, tmp_path, {}, "http://127.0.0.1:17770", "sequential",
                               trial_runner=run, pool_factory=ThreadPoolExecutor)
    assert len(calls) == 8
    assert len(set(calls)) == 8
    assert result["passed"] is False
    assert result["total_tokens"] is None
    errors = [r for r in result["trials"] if r["status"] == "error"]
    assert len(errors) == 1 and errors[0]["total_tokens"] is None


@pytest.mark.parametrize("changes", [{"passed": False}, {"usage_complete": False, "total_tokens": None}])
def test_eight_records_are_not_enough_to_pass(probe, tmp_path, changes):
    result = probe.run_batches(TASKS, tmp_path, {}, "http://127.0.0.1:17770", "sequential",
                               trial_runner=lambda spec: {**unit_result(spec), **changes},
                               pool_factory=ThreadPoolExecutor)
    assert result["passed"] is False


@pytest.mark.parametrize("tokens", [(10, 2), (0, 0), (10, 0), (None, 2)])
def test_usage_missing_or_defaulted_zero_cannot_pass(probe, tokens):
    client = SimpleNamespace(prompt_tokens=tokens[0] or 0, completion_tokens=tokens[1] or 0, call_count=1,
        request_log=[{"prompt_tokens": tokens[0], "completion_tokens": tokens[1],
                      "model": "Qwen/Qwen3.8-27B", "provider": "modelscope_local"}])
    usage = probe.checked_usage(client, {"prompt_tokens": 0, "completion_tokens": 0, "call_count": 0, "log_length": 0}, complete=True)
    assert usage["usage_complete"] is (tokens == (10, 2))
    assert usage["total_tokens"] == (12 if tokens == (10, 2) else None)


def trial_spec(tmp_path, index=0):
    return {"trial_id": str(index), "round": 1, "mode": "sequential", "task": TASKS[index],
            "job": {"arm": "baseline", "condition": "clean", "topology": "sequential"},
            "ledger_path": str(tmp_path / f"{index}.sqlite3"), "settings": {},
            "base_url": "http://127.0.0.1:17770"}


def test_worker_fresh_state_and_operation_error_receipts(probe, tmp_path):
    clients, ledgers = [], []
    factory, executors, _ = executor_factory()
    def client_factory(settings):
        client = SimpleNamespace(prompt_tokens=0, completion_tokens=0, call_count=0, request_log=[])
        clients.append(client)
        return client
    async def trial(task, job, executor, client, *, ledger_path):
        ledgers.append(ledger_path)
        executor.add_to_cart(task)
        executor.reobserve_cart(task)
        client.call_count = 1
        client.prompt_tokens, client.completion_tokens = 10, 2
        client.request_log.append({"prompt_tokens": 10, "completion_tokens": 2,
                                   "model": probe.runner.MODEL, "provider": probe.runner.PROVIDER})
        if task["task_id"] == TASKS[1]["task_id"]:
            exc = RuntimeError("secret must not be recorded")
            exc.partial_trial = {"events": [{"event_id": 0}]}
            raise exc
        return {"final_task_success": True, "environment_task_success": True, "decision_correct": True,
                "evidence_acceptance_errors": 0, "fault_events": [], "action_outcome_unknown": False,
                "model": probe.runner.MODEL, "provider": probe.runner.PROVIDER}
    rows = [probe.execute_trial(trial_spec(tmp_path, i), client_factory=client_factory,
                               executor_factory=factory, trial=trial) for i in range(2)]
    assert len({id(c) for c in clients}) == len({id(e) for e in executors}) == len(set(ledgers)) == 2
    assert rows[0]["passed"] is True and rows[0]["total_tokens"] == 12
    assert rows[1]["passed"] is False and rows[1]["usage_complete"] is False
    assert rows[1]["model_calls"] == 1 and rows[1]["total_tokens"] is None
    assert rows[1]["partial_trial"] == {"events": [{"event_id": 0}]}
    assert all(r["http_receipts"] for r in rows)
    assert "secret" not in json.dumps(rows)


def offline_spawn_worker(value):
    import os
    import threading
    from mas_faults.llm_client import request_deadline
    with request_deadline(5):
        return value, os.getpid(), threading.current_thread() is threading.main_thread()


def test_real_spawn_pool_supports_signal_deadline_offline(probe):
    import os
    with probe._process_pool(max_workers=2) as pool:
        futures = [pool.submit(offline_spawn_worker, i) for i in range(2)]
        rows = [future.result(timeout=30) for future in futures]
    assert [r[0] for r in rows] == [0, 1]
    assert all(r[1] != os.getpid() and r[2] for r in rows)


def test_success_output_provenance_and_whole_probe_lock(probe, args):
    states = {"locked": False, "transport": False}
    @contextmanager
    def lock():
        states["locked"] = True
        try:
            yield
        finally:
            states["locked"] = False
    @contextmanager
    def transport():
        assert states["locked"]
        states["transport"] = True
        try:
            yield
        finally:
            states["transport"] = False
    factory, _, _ = executor_factory()
    def preflight(settings):
        assert all(states.values())
        assert (args.output_dir / "http_gate.json").exists()
        return None, {"unit_only": True}
    def batches(*a):
        assert all(states.values())
        return probe.run_batches(*a, trial_runner=unit_result, pool_factory=ThreadPoolExecutor)
    result = probe.run_probe(args, workflow_lock=lock, transport=transport, platform_name="linux",
                             preflight=preflight, executor_factory=factory, batch_runner=batches)
    assert result["passed"] is True and result["formal_matrix_started"] is False
    assert not any(states.values())
    assert args.output_dir.stat().st_mode & 0o777 == 0o700
    config = json.loads((args.output_dir / "probe_manifest.json").read_text())["config"]
    assert config["tasks"] == TASKS
    assert config["task_manifest_sha256"] == hashlib.sha256(args.task_manifest.read_bytes()).hexdigest()
    assert "scripts/probe_multimechanism_parallel.py" in config["source_hashes"]
    assert "run_shopping_multimechanism.py" in config["source_hashes"]
    assert "unit-only" not in json.dumps(config)
    assert len((args.output_dir / "trials.jsonl").read_text().splitlines()) == 8
    assert len((args.output_dir / "trials.csv").read_text().splitlines()) == 9
    assert "两路" in (args.output_dir / "summary_zh.md").read_text()
    for metrics in result["by_mode"].values():
        assert metrics["prompt_tokens"] == 40 and metrics["completion_tokens"] == 8
        assert metrics["completed_trials"] == 4 and metrics["failed_trials"] == 0
        assert metrics["completed_throughput_per_second"] > 0


def test_changed_manifest_refuses_before_output(probe, args, monkeypatch):
    original = probe.select_tasks
    def changed(*a):
        selected = original(*a)
        args.task_manifest.write_text(json.dumps([TASKS[1], TASKS[0]]))
        return selected
    monkeypatch.setattr(probe, "select_tasks", changed)
    def forbidden(*a, **kw):
        pytest.fail("changed inputs must never reach a transport")
    with pytest.raises(ValueError, match="manifest changed"):
        probe.run_probe(args, workflow_lock=nullcontext, platform_name="linux",
                        transport=forbidden, executor_factory=forbidden, preflight=forbidden)
    assert not args.output_dir.exists()


@pytest.mark.parametrize("field", ["cart_id_sha256", "session_id"])
def test_reused_trial_cart_or_runtime_session_cannot_pass(probe, tmp_path, field):
    def run(spec):
        row = unit_result(spec)
        if field == "session_id":
            row["result"][field] = "reused"
        else:
            row[field] = "a" * 64
        return row
    result = probe.run_batches(TASKS, tmp_path, {}, "http://127.0.0.1:17770", "sequential",
                               trial_runner=run, pool_factory=ThreadPoolExecutor)
    assert result["passed"] is False
    assert result["trial_isolation_verified"] is False


def successful_unit_trial_result(probe):
    return {"final_task_success": True, "environment_task_success": True, "decision_correct": True,
            "evidence_acceptance_errors": 0, "fault_events": [], "action_outcome_unknown": False,
            "model": probe.runner.MODEL, "provider": probe.runner.PROVIDER}


@pytest.mark.parametrize("tamper", ["foreign_500", "foreign", "http500", "missing_cart", "empty", "bad_index", "result_disagrees"])
def test_worker_success_claim_requires_real_executor_receipts(probe, tmp_path, tamper):
    client = SimpleNamespace(prompt_tokens=0, completion_tokens=0, call_count=0, request_log=[])
    async def trial(task, job, executor, client, **kwargs):
        executor.add_to_cart(task)
        executor.reobserve_cart(task)
        client.prompt_tokens, client.completion_tokens, client.call_count = 10, 2, 1
        client.request_log = [{"prompt_tokens": 10, "completion_tokens": 2,
                               "model": probe.runner.MODEL, "provider": probe.runner.PROVIDER}]
        result = successful_unit_trial_result(probe)
        if tamper == "result_disagrees":
            result["http_receipts"] = []
        else:
            corrupt_receipts(executor.http_receipts, tamper)
        return result
    row = probe.execute_trial(trial_spec(tmp_path), client_factory=lambda _: client,
                              executor_factory=lambda _: UnitExecutor("own", []), trial=trial)
    assert row["status"] == "completed" and row["usage_complete"] is True
    assert row["passed"] is False
    assert row["http_receipts_verified"] is False


def corrupt_receipts(receipts, tamper):
    if tamper == "empty":
        receipts.clear()
        return
    receipt = receipts[-1]
    if tamper in {"foreign", "foreign_500"}:
        receipt["guest_cart_id_sha256"] = "f" * 64
    if tamper in {"http500", "foreign_500"}:
        receipt["status_code"] = 500
    if tamper == "missing_cart":
        receipt["guest_cart_id_sha256"] = None
    if tamper == "bad_index":
        receipt["receipt_index"] = 0


@pytest.mark.parametrize("tamper", ["foreign_500", "missing_cart", "empty", "result_disagrees"])
def test_parent_revalidates_receipts_not_just_worker_passed_flag(probe, tmp_path, tamper):
    def run(spec):
        row = unit_result(spec)
        row["http_receipts_verified"] = True
        if tamper == "result_disagrees":
            row["result"]["http_receipts"] = []
        else:
            corrupt_receipts(row["http_receipts"], tamper)
        return row
    result = probe.run_batches(TASKS, tmp_path, {}, "http://127.0.0.1:17770", "sequential",
                               trial_runner=run, pool_factory=ThreadPoolExecutor)
    assert result["passed"] is False
    assert result["trial_isolation_verified"] is False
    assert all(not row["passed"] for row in result["trials"])


@pytest.mark.parametrize("purpose", [None, "add_to_cart.create_cart", "add_to_cart.add_item",
                                    "add_quantity.add_item", "set_quantity.set_item", "reobserve_cart.items"])
def test_http_gate_missing_cart_binding_fails_for_cart_operations(probe, purpose):
    class CorruptExecutor(UnitExecutor):
        def reobserve_cart(self, task):
            result = super().reobserve_cart(task)
            for receipt in self.http_receipts:
                if purpose is None or receipt["purpose"] == purpose:
                    receipt["guest_cart_id_sha256"] = None
            return result
    factory = lambda _: CorruptExecutor(__import__("uuid").uuid4().hex, [])
    gate = probe.http_isolation_gate(TASKS, "http://127.0.0.1:17770", executor_factory=factory)
    assert gate["passed"] is False


def test_http_gate_allows_only_actual_initial_pre_cart_receipt(probe):
    factory, _, _ = executor_factory()
    gate = probe.http_isolation_gate(TASKS, "http://127.0.0.1:17770", executor_factory=factory)
    assert gate["passed"] is True
    for flow in gate["flows"]:
        unbound = [r for r in flow["http_receipts"] if r["guest_cart_id_sha256"] is None]
        assert len(unbound) == 1
        assert unbound[0]["receipt_index"] == 0 and unbound[0]["purpose"] == "add_to_cart.product_page"


@pytest.mark.parametrize("failure", ["failed", "unknown_usage", "error"])
def test_failed_parallel_batches_never_claim_speedup(probe, tmp_path, failure):
    clock = iter([0, 10, 20, 25, 30, 34, 40, 48])
    def run(spec):
        row = unit_result(spec)
        if spec["mode"] == "parallel":
            if failure == "failed":
                row["passed"] = False
            elif failure == "unknown_usage":
                row.update(usage_complete=False, total_tokens=None)
            else:
                row["status"] = "error"
        return row
    result = probe.run_batches(TASKS, tmp_path, {}, "http://127.0.0.1:17770", "sequential",
                               trial_runner=run, pool_factory=ThreadPoolExecutor, clock=lambda: next(clock))
    assert [r["speedup"] for r in result["rounds"]] == [2, 2]
    assert result["two_way_faster_in_both_rounds"] is False
    assert all(r["comparable"] is False for r in result["rounds"])


def offline_expiring_worker():
    import os
    import signal
    import time
    from mas_faults.llm_client import request_deadline
    handler = signal.getsignal(signal.SIGALRM)
    started = time.monotonic()
    try:
        with request_deadline(1):
            time.sleep(3)
    except TimeoutError:
        return {"pid": os.getpid(), "expired": True, "elapsed": time.monotonic() - started,
                "restored": signal.getsignal(signal.SIGALRM) == handler and signal.getitimer(signal.ITIMER_REAL) == (0, 0)}
    return {"pid": os.getpid(), "expired": False}


def test_spawn_deadline_actually_expires_and_worker_is_reusable(probe):
    with probe._process_pool(max_workers=1) as pool:
        expired = pool.submit(offline_expiring_worker).result(timeout=10)
        reused = pool.submit(offline_spawn_worker, "still healthy").result(timeout=10)
    assert expired["expired"] is True and expired["restored"] is True
    assert 0 < expired["elapsed"] < 3
    assert reused == ("still healthy", expired["pid"], True)
