"""Build a static methods supplement using reviewed prose and archived excerpts."""
import html
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SITE=ROOT/'site'
def esc(x):return html.escape(str(x))
def source(path,label):
 return f'<a href="https://github.com/SonGoKu21/mas_communication/blob/538c4a84f7732d85b7ca26154d2f8f5be9ac2871/{path}">{label} ↗</a>'
def excerpt(title,value):return f'<details><summary>{title}</summary><pre>{esc(json.dumps(value,ensure_ascii=False,indent=2))}</pre></details>'
tax=json.loads((ROOT/'content/taxonomy.json').read_text())
refs=json.loads((ROOT/'content/references.json').read_text())['references']
refmap={r['key']:(i,r) for i,r in enumerate(refs,1)}
def cite(keys):
    links=[]
    for key in keys.split(','):
        i,r=refmap[key.strip()]
        links.append(f'<a class="citation" href="#ref-{i}" title="{esc(r["title"])}">[{i}]</a>')
    return ' '.join(links)
rows=''.join(f'<tr><td>{esc(r["layer"])}</td><td>{esc(r["name"])}</td><td>{esc(r["description"])}</td><td>{cite(r["references"])}</td></tr>' for r in tax)
reference_items=[]
for i,r in enumerate(refs,1):
    publication=r['venue']
    if r['volume']: publication+=' '+r['volume']
    if r['number']: publication+=' ('+r['number']+')'
    if r['pages']: publication+=', pp. '+r['pages']
    title=f'<a href="{esc(r["url"])}">{esc(r["title"])}</a>' if r['url'] else esc(r['title'])
    note=f' <span class="muted">{esc(r["note"])}</span>' if r['note'] else ''
    doi=f' DOI: <a href="https://doi.org/{esc(r["doi"])}">{esc(r["doi"])}</a>.' if r['doi'] else ''
    authors='; '.join(' '.join(reversed(a.split(', ',1))) if ', ' in a else a for a in r['authors'].split(' and '))
    publication_text=(' '+esc(publication).rstrip('.')+'.') if publication else ''
    year=esc(r['year']).rstrip('.')
    reference_items.append(f'<li id="ref-{i}"><span class="ref-number">[{i}]</span> {esc(authors)}. {year}. {title}.{publication_text}{doi}{note} <a class="ref-back" href="#taxonomy">↑ Taxonomy</a></li>')
references='<section id="references"><p class="eyebrow">BIBLIOGRAPHY</p><h2>References</h2><p>References are numbered within this methods supplement. Entries without a publication year are marked n.d.</p><p><a href="data/methodology-references.bib" download>Download references · BibTeX ↓</a></p><ol class="reference-list">'+''.join(reference_items)+'</ol></section>'

fault=json.loads((SITE/'data/runs/44e3f15a85969707e3f2270f.json').read_text())
clean=json.loads((SITE/'data/runs/97888106e815e717ba7bb435.json').read_text())
event=next(e for e in fault['events'] if e.get('fault_applied'))
accepted=next(e for e in fault['events'] if e['source_agent']=='Verifier')
case=excerpt('1 · Matched clean record: configuration and endpoint',clean['metadata'])
case+=excerpt('2 · Actual interception: event identity and exposure',{k:event.get(k) for k in ['step_id','abstract_step','source_agent','target_agent','message_id','fault_applied','fault_parameters','observed_A_symptom','observed_runtime_effect']})
case+=excerpt('3 · Original evidence_result',event['original_message']['payload']['evidence_result'])
case+=excerpt('4 · Delivered evidence_result',event['delivered_message']['payload']['evidence_result'])
case+=excerpt('5 · Downstream use: Verifier → Coordinator',accepted['delivered_message'])
case+=excerpt('6 · Archived consequence, endpoint and handling fields',{k:fault['metadata'][k] for k in ['consequences','endpoint','response','source_file','source_line','source_run_id']})
ops=[
('timeliness_deadline_step4','Timeliness · I4','A handoff exceeds its configured delivery budget and is not delivered.','Inspect deadline_ms and the delivery-event record. Do not infer exposure from elapsed run time alone.'),
('non_delivery_step2','Availability · I2','The selected action request is withheld before receiver consumption.','An unreached target is not applied. Trace the work that the missing request would have enabled.'),
('non_delivery_step4','Availability · I4','Generated evidence is withheld on the selected downstream handoff.','Inspect other recorded edges: evidence may remain available through a bypass path.'),
('semantic_corruption_step4','Semantic integrity · I4','Task-critical meaning in a processable evidence carrier is changed.','The replacement depends on the domain adapter. Compare original/delivered fields and subsequent use; a parseable message is not necessarily correct.'),
('valid_partial_message_step4','Completeness · I4','A processable carrier retains an answer or partial content while required evidence is removed.','Inspect the task-specific contract. Missing evidence does not by itself mean the numeric answer is wrong.'),
('stale_replay_step4','Freshness / association · I4','Prior-task or prior-session evidence is supplied at the current handoff.','Inspect task/session/version metadata and actual payload differences. A replay request without prior evidence does not establish changed exposure.')]
opcards=''.join(f'<details class="operator"><summary><code>{name}</code><span>{kind}</span></summary><p>{desc}</p><p><b>Exposure check.</b> {check}</p></details>' for name,kind,desc,check in ops)
sources=''.join('<li>'+source(p,l)+'</li>' for p,l in [
('src/mas_faults/llm/application_fault_matrix.py','Supported operator-position registry'),('src/mas_faults/llm/communication_interceptor.py','Generic carrier interception'),('src/mas_faults/webarena_admin_main_matrix.py','Admin condition definitions and domain-specific transformations'),('src/mas_faults/llm/propagation_evaluator.py','Historical Shopping-oriented propagation rules'),('reports/rq123_six_condition_inputs_20260916_v2/analysis_config.json','Frozen common-matrix selection and repeats'),('analysis/rq123_20260915/mas_faults/unified_fse_analysis.py','Historical cross-domain analysis snapshot'),('mas_rq4_20260914','Separate RQ4 implementation snapshot')])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Extended Methodology · MAS Fault Observatory</title><meta name="description" content="Communication-fault taxonomy, injection boundaries, operators, evidence criteria and archived worked example."><link rel="stylesheet" href="styles.css"><link rel="icon" href="mark.svg" type="image/svg+xml"></head><body class="methodology-page">
<header><a class="brand" href="./"><img src="mark.svg" width="32" height="32" alt=""><span>MAS <b>Fault Observatory</b></span></a><span class="edition">RESEARCH ARTIFACT / 2026</span><span class="readonly">Extended methods · archived evidence</span></header>
<nav class="mainnav" aria-label="Primary"><a href="./">Home &amp; explorer</a><a href="methodology.html" aria-current="page">Methodology</a><a href="data/manifest.json">Evidence manifest ↓</a></nav>
<main class="methodology"><div class="method-intro"><p class="eyebrow">METHODS SUPPLEMENT</p><h1>Extended methodology</h1><p class="hero-subtitle">From a communication intervention to an auditable outcome.</p><p>This supplement expands the paper’s taxonomy and two-phase fault-injection pipeline. It connects the methodological definitions to implementation snapshots and recorded examples. The framework is broader than the conditions evaluated in any one experiment.</p></div>
<nav class="method-toc" aria-label="Method sections"><a href="#taxonomy">01 Taxonomy</a><a href="#boundaries">02 Injection boundaries</a><a href="#operators">03 Operators</a><a href="#evaluation">04 A / M / O / B</a><a href="#walkthrough">05 Worked example</a><a href="#protocol">06 Protocol &amp; reproduction</a><a href="#references">References</a></nav>
<section id="taxonomy"><p class="eyebrow">01 · SCOPE OF THE MODEL</p><h2>A cross-layer taxonomy</h2><p>The taxonomy draws on established dependability concepts __FOUNDATIONS__ and the representative sources cited in each row.</p><div class="method-flow"><article><b>P / D / N / T</b><p>Where a lower-stack disturbance originates.</p></article><span aria-hidden="true">→</span><article><b>A · Receiver exposure</b><p>What changes at the receiving application boundary.</p></article><span aria-hidden="true">→</span><article><b>M · MAS consequence</b><p>How affected information changes downstream state or behavior.</p></article></div><p>The mapping is conditional: lower-stack disturbances may be masked, and different sources can produce the same visible symptom. A-layer faults can also originate directly in agent-runtime delivery, ordering, association or structured-message handling. Local model reasoning, parameters, activations and training-state errors are outside this taxonomy.</p><p><b>Coverage boundary.</b> The table is a classification, not a claim that every entry was injected in every benchmark. The 3,780 source-mapping executions are controlled fixtures; they do not carry MAS task-outcome scores.</p><details><summary>Full taxonomy · 29 entries, with linked references</summary><p>Numbered citations link to full bibliographic entries below.</p><div class="table-scroll"><table><thead><tr><th>Layer</th><th>Fault / effect</th><th>Description</th><th>References</th></tr></thead><tbody>__TAXONOMY__</tbody></table></div></details></section>
<section id="boundaries"><p class="eyebrow">02 · PHASE I — FAULT GENERATION</p><h2>Intercept a concrete communication dependency</h2><p>Select the task, workflow, model configuration, repetition, operator and parameters. Identify the selected edge, carrier and task/session association. The interceptor acts after sender-side production and before receiver-side consumption:</p><div class="formula">φ<sub>f,θ</sub>(m<sub>t</sub>, S<sub>t</sub>) → (m′<sub>t</sub>, S′<sub>t</sub>)</div><p>Here m is the carrier and S is the relevant communication/runtime state. Clean runs use the same instrumentation with an identity operation. Provider requests/responses, local model internals and tool semantics are outside the intervention boundary.</p><div class="boundary-grid"><article><h3>I2 · Action request</h3><p>An upstream instruction or tool request enables subsequent work. Losing it can prevent evidence from being generated.</p><small>Inspect: requested action, sending edge, delivery count, downstream work.</small></article><article><h3>I3 · Observation</h3><p>An environment or tool result returns to the agent workflow. Delayed, displaced or incomplete observations can change available state.</p><small>Inspect: tool result, state version, ordering and actual receiver input.</small></article><article><h3>I4 · Evidence handoff</h3><p>Produced results reach a verifier or decision agent. A fault here changes access to, or interpretation of, existing evidence.</p><small>Inspect: evidence carrier, receiver decision, alternate information paths.</small></article></div><figure><a href="figures/fig-3.png"><img src="figures/fig-3.png" alt="Sequential, Flat and Hierarchical workflows and injection boundaries" loading="lazy"></a><figcaption>Paper Figure 3. Workflow boundaries. Click the figure to view the full image.</figcaption></figure><p class="home-note">Step 2/3/4 are abstract dependency types, not necessarily the second/third/fourth event in a trace. Eligibility varies by operator. The common matrix tests I2 and I4; describing I3 does not imply it is included in that matrix.</p></section>
<section id="operators"><p class="eyebrow">03 · WHAT WAS CHANGED</p><h2>Operator implementation and evaluated conditions</h2><p>The common matrix contains clean plus six condition-position cells. Two cells are non-delivery at different positions; this is not a count of six distinct fault families. Expand a cell for its intervention and exposure check.</p>__OPERATORS__<details><summary>Broader implemented operator inventory</summary><p>The generic registry also lists delay, timeout, channel interruption, endpoint unavailability, omission, message corruption, malformed JSON, truncation, duplication, reordering, schema mismatch, stale replay, runtime communication-state corruption, message-channel instruction injection and contract violation. Generic scenario handling additionally includes valid-partial and partition-equivalent cases. This inventory is not the main-study evaluation matrix.</p><p>Examples from the generic interceptor: truncation keeps the first half of serialized content; malformed JSON creates an unfinished wrapper; schema mismatch renames selected keys; contract violation changes selected field types; valid-partial removes product/evidence keys. These are implementation examples, not universal semantics for every domain adapter.</p><p>Generic FaultScenario defaults are delay_ms=1000 and timeout_ms=500. They are constructor defaults, not verified parameter values for every published run. Use each run’s fault_parameters and event records for actual settings.</p></details><p class="home-note">Legacy A1–A15 codes and names belong to particular implementation snapshots. Read the recorded descriptive symptom and local registry together; do not treat those numeric codes as a universal mapping to the paper’s seven A-layer families.</p><details><summary>Implementation and analysis sources</summary><p>Links pin the published code snapshot used for this supplement. The restored snapshot has not been verified as identical to every historical execution environment.</p><ul>__SOURCES__</ul></details></section>
<section id="evaluation"><p class="eyebrow">04 · PHASE II — PROPAGATION EVALUATION</p><h2>Keep exposure, propagation and outcome separate</h2><div class="table-scroll"><table><thead><tr><th>Variable</th><th>Required evidence</th><th>What does not establish it</th></tr></thead><tbody><tr><td><b>A · Exposure</b></td><td>Original/delivered carrier differences or a delivery-event trace confirming the intended receiver-visible change.</td><td>A scheduled fault, a configuration flag alone, or final task failure.</td></tr><tr><td><b>M · Consequence</b></td><td>A trace-linked downstream state or behavior change. Semantic consequences require affected information to be accepted or used.</td><td>Changed text that no downstream agent uses; task failure alone does not establish the propagation path.</td></tr><tr><td><b>O · Outcome</b></td><td>The task evaluator’s result under that adapter’s evaluation contract.</td><td>Inferring failure from A or M. A successful endpoint can coexist with a consequence.</td></tr><tr><td><b>B · Handling response</b></td><td>A recorded handling reaction after exposure.</td><td>A complete detection–correction–state-restoration chain or a verified recovery rate.</td></tr></tbody></table></div><details open><summary>Decision procedure and boundary cases</summary><ol><li>Check whether execution reached the intended event. If not, record not applied.</li><li>Verify actual exposure, including delivery count/timing for missing carriers. Preserve an unknown state when the available archive cannot establish the change.</li><li>Follow the dependency through actions, aggregation, accepted evidence, verification and termination. For omission, identify the required action or state that can no longer complete.</li><li>Read the independent evaluator result. Keep correct-answer and evidence-contract requirements distinct when the adapter combines them.</li><li>Report the historical handling flag separately. Do not relabel it as strict recovery.</li></ol></details><p class="home-note">These are the paper’s interpretation criteria. Historical labels are retained as recorded; this website does not claim fresh independent annotation or complete re-adjudication. Some legacy labeling rules incorporate decision/completeness/outcome fields. Inspect their code and the trace before interpreting a label as independently measured causal evidence.</p><div class="boundary-grid"><article><h3>Changed but rejected</h3><p>A may be established while a particular semantic-acceptance M label is unsupported. Rejection can still alter workflow behavior.</p></article><article><h3>Propagated yet successful</h3><p>A recorded consequence and final success can coexist; another path may supply useful evidence.</p></article><article><h3>Correct answer, failed contract</h3><p>An endpoint may fail because required evidence is missing even when a candidate answer is correct.</p></article></div></section>
<section id="walkthrough"><p class="eyebrow">05 · ONE ARCHIVED EXECUTION</p><h2>From a top-one request to an accepted top-two answer</h2><p>Task 033 · WebArena Admin, original task 41 · Qwen3.5-9B · Sequential · repetition 1. The user asks “List the top 1 search terms in my store”. The matched clean execution succeeds. At I4, the fault run changes the candidate from <b>hollister</b> to <b>hollister, Joust Bag</b> while retaining the ranking table. The Verifier accepts the altered answer and describes the request as top two; the archived endpoint fails.</p><p>Only the nested evidence_result projections are shown in steps 3 and 4 below. Open the original record for the entire carrier. Event routing identifies Evidence Worker → Verifier, while the carrier’s embedded target_agent says Coordinator; both historical fields are preserved rather than normalized.</p><div class="case-evidence">__CASE__</div><p><a class="evidence-link" href="./#run=44e3f15a85969707e3f2270f">Open fault run</a> · <a href="./#run=97888106e815e717ba7bb435">Open matched clean run</a> · <a href="data/runs/44e3f15a85969707e3f2270f.json" download>Download archived fault evidence ↓</a></p><p class="home-note">This example demonstrates a traceable semantic-acceptance failure. It does not explain all aggregate failures or establish a topology-only causal effect. The recorded response flag is false; no strict recovery is claimed.</p></section>
<section id="protocol"><p class="eyebrow">06 · EXPERIMENT PROTOCOL</p><h2>Reproduce the artifact and understand its limits</h2><h3>Common-matrix design</h3><p><b>100 tasks × 3 model configurations × 3 topologies × 7 conditions × 3 repetitions = 18,900 executions.</b> The seven conditions are clean plus the six cells above. Tasks span Shopping (30), Admin (20), Reddit (15), SWE-bench (20) and TheAgentCompany (15). Repetitions identify repeated executions; stored traces do not establish independent sampling seeds.</p><h3>Matching and denominators</h3><p>For a clean/fault contrast, match collection, domain, task, model, topology and repetition. Report the differing condition and any other changed dimensions. Applied-fault analyses exclude scheduled-but-unreached interventions; overall endpoint summaries and clean-conditional losses have different denominators. A clean-conditional loss conditions on successful matched clean executions. Preserve the analysis script’s aggregation and missing-pair rules when reproducing a reported percentage.</p><p>Keep the Reddit extension (2,835), source-mapping fixtures (3,780), and RQ4 factorial (864), diagnostic (90) and finite-exposure (144) studies separate. Two planned exposures do not guarantee two realized exposures. SWE/TAC fault trials use frozen evidence rather than a fresh end-to-end benchmark execution per fault.</p><h3>Record schema and availability</h3><div class="table-scroll"><table><thead><tr><th>Record group</th><th>Fields to inspect when present</th></tr></thead><tbody><tr><td>Identity and configuration</td><td>task_id, source_run_id, model, topology, condition, repetition, source_file, source_line</td></tr><tr><td>Communication exposure</td><td>original_message, delivered_message(s), message_id, source_session, state_version, source_agent, target_agent, fault_parameters, fault_applied</td></tr><tr><td>Timing and downstream behavior</td><td>send/delivery timestamps, event order, accepted decisions, actions, final answer and termination evidence</td></tr><tr><td>Archived evaluation</td><td>observed_A_symptom, consequences, endpoint, response, adapter-specific verdict fields</td></tr></tbody></table></div><p>The current export indexes 26,613 records and bundles detailed evidence for 6,800. Summary-only records do not supply a full trajectory. Field presence varies by collection and historical runner. Separate logs retain recorded order and are not artificially synchronized; absent fields are not reconstructed. Deployment identifiers are redacted.</p><h3>Minimal local replay · no models or benchmark services</h3><pre>git clone https://github.com/SonGoKu21/mas_communication.git
cd mas_communication
python3 -m http.server 8000 --directory web/site
# Open http://localhost:8000/</pre><h3>Validate the exported artifact</h3><pre>python3 -m unittest discover -s web/tests -v
python3 web/tools/verify.py
python3 web/tools/build_methodology.py</pre><p>These commands validate or render the static artifact. They do not recompute paper results. Full experiment execution requires separately configured models, benchmark services and data. Raw JSONL inputs are not published; analysis configuration files specify expected paths. See the repository for component availability and validation results.</p><p>__README__ · __VALIDATION__ · <a href="data/task-map.json">Task identity mapping</a> · <a href="data/manifest.json">Manifest and source digests</a></p></section>
__REFERENCES__</main><footer><span>MAS Communication Fault Observatory</span><span>Methods supplement</span></footer></body></html>'''
page=page.replace('__REFERENCES__',references).replace('__FOUNDATIONS__',cite('avizienis2004dependability,iso7498,rfc1122')).replace('__TAXONOMY__',rows).replace('__OPERATORS__',opcards).replace('__SOURCES__',sources).replace('__CASE__',case).replace('__README__',source('README.md','Environment and full reproduction boundaries')).replace('__VALIDATION__',source('VALIDATION.md','Recorded code validation status'))
(SITE/'methodology.html').write_text(page)
print('Built methodology: 29 taxonomy entries, six evaluated cells, source-backed case excerpts.')
